#!/bin/bash

if [[ -z "${1}" ]]; then
  id="TNA/R39/3506/3506D/006/11"
else
  id="${1}"
fi

fmp_access_token="eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImowV2dNN2cyQnUxT0Y4YjBpT3RTZyJ9.eyJodHRwczovL3d3dy5maW5kbXlwYXN0LmNvbS9jb25uZWN0aW9uIjoiYWNjb3VudCIsImh0dHBzOi8vd3d3LmZpbmRteXBhc3QuY29tL21lbWJlcl9pZCI6NDE3MjIxMzYyLCJodHRwczovL3d3dy5maW5kbXlwYXN0LmNvbS9leHBlcmltZW50YXRpb25fdHJhY2tpbmdfa2V5IjoiYjYwY2EwMWYtMGE0Yi00OTk1LTg1MmUtOTdiNzQ4NmU5MjI2IiwiaXNzIjoiaHR0cHM6Ly9hdXRoLmZpbmRteXBhc3QuY29tLyIsInN1YiI6ImF1dGgwfDY4MTBiMzc0MjRiNmUyNGQ5ZTcxOWQ2NCIsImF1ZCI6WyJodHRwcz90823jag98wjjh43ew98jgjeidrn98g3490jg903ej9gk3g3odHRwczovL2ZtcC1wcm9kdWN0aW9uLmV1LmF1dGgwLmNvbS91c2VyaW5mbyJdLCJpYXQiOjE3NDU5MjY4MjEsImV4cCI6MTc0NTkyODYyMSwic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBlbWFpbCBvZmZsaW5lX2FjY2VzcyIsImF6cCI6InRZWTZOZnFyRDZaSEhSbW5SU1lrMUtwWUkwNXZHblJwIn0.lrVp02Vq3wbID0HCoysPITqdAyzPmuy7vuIfLF1S966yiHPoC3PHfW9YU_--rupJQoDJqGuJJcMXMG0_ta5OFzRrsxIZGGkc0X0DCk_kmtxCM6t1_G0vgOjbCCfHt6_eIK-lCq8fkrixMcqmHtQhW8izHpNnh0jwTF_ZXMm_8pQZVRhRNDjE2-yyUp-OcbZGm_TyTvC_5XI9rWHRGnK93xH4nnBITAnHqYHy5dzB6AoylYR7mNp-ef7vRuTC4xaZ_8NuIEsMEplM2iUHo2WS229lKyc46aAv6IjoZFZWVlsAmKaNbuWL9OX7RC_XF-H-YKjIxb_KnHUqAMLkJR0omw"

curl 'https://www.findmypast.co.uk/titan/marshal/graphql' -H 'content-type: application/json' -H 'Cookie:fmp_access_token='"${fmp_access_token}"';' --data-raw '{"operationName":"fulfillTranscript","variables":{"showCorrected":false,"recordId":"'"${id}"'"},"query":"mutation fulfillTranscript($recordId: String!, $confirmedPurchase: Boolean, $showCorrected: Boolean = false) {\n  fulfillTranscript(recordId: $recordId, confirmedPurchase: $confirmedPurchase) {\n    fulfillmentTypeKey\n    allowedPlanIds\n    action\n    actionCode\n    transcript {\n      id\n      ...transcript\n      __typename\n    }\n    record {\n      id\n      transcript {\n        id\n        recordMetadataId\n        __typename\n      }\n      pdf {\n        id\n        __typename\n      }\n      image {\n        id\n        recordMetadataId\n        __typename\n      }\n      __typename\n    }\n    __typename\n  }\n}\n\nfragment transcript on FulfilledTranscript {\n  id\n  contextualContent\n  contextualContentData {\n    id\n    recordMetadataId\n    geocode {\n      latitude\n      level\n      longitude\n      mapLayer\n      __typename\n    }\n    address {\n      place\n      county\n      district\n      __typename\n    }\n    entities {\n      code\n      type\n      value\n      __typename\n    }\n    __typename\n  }\n  fields {\n    fieldId\n    value\n    __typename\n  }\n  recordSet {\n    id\n    fields {\n      fieldId\n      displayLabel\n      displayOnSite\n      hideEmpty\n      transcriptionDisplayOrder\n      relatedRecordDisplayOrder\n      __typename\n    }\n    canReportError\n    __typename\n  }\n  transcriptFulfillableItem {\n    id\n    recordMetadataId\n    isPurchased\n    isNationalTrust\n    __typename\n  }\n  imageFulfillableItem {\n    id\n    recordMetadataId\n    mediaSource\n    __typename\n  }\n  otherPeopleRelatedRecords {\n    title\n    records {\n      id\n      fields {\n        value\n        fieldId\n        __typename\n      }\n      __typename\n    }\n    __typename\n  }\n  lastCorrectedBy @include(if: $showCorrected) {\n    ... on TranscriptLastCorrectedData {\n      __typename\n      dateCorrected\n      userProfile {\n        id\n        ... on ActiveUserProfile {\n          username\n          profilePicture\n          __typename\n        }\n        ... on GDPRDeletedUserProfile {\n          username\n          __typename\n        }\n        __typename\n      }\n    }\n    __typename\n  }\n  __typename\n}\n"}'
